 
name: Build
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game:"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 升级 actions/checkout 到最新版本（v4）
      - uses: actions/checkout@v4

      # 2. 升级 actions/setup-java 到最新版本（v4）
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      # 3. 构建步骤适配
      - name: Build and modify files
        run: |
          # 确保 gradlew 可执行
          chmod +x ./gradlew
          
          # 处理输入参数中的特殊字符（如斜杠、空格）
          ESCAPED_PACKAGE_NAME=$(echo "${{ github.event.inputs.package_name }}" | sed 's/\//\\\//g')
          
          # 修改 module.gradle 和 game.h
          sed -i "s/moduleDescription = \"/moduleDescription = \"($ESCAPED_PACKAGE_NAME) /g" module.gradle
          sed -i "s/com\.game\.packagename/$ESCAPED_PACKAGE_NAME/g" module/src/main/cpp/game.h
          
          # 执行构建
          ./gradlew :module:assembleRelease

      # 4. 检查输出目录是否存在
      - name: Verify output directory
        run: ls -R out/magisk_module_release

      # 5. 升级 actions/upload-artifact 到 v4
      - uses: actions/upload-artifact@v4
        with:
          name: zygisk-il2cppdumper
          path: out/magisk_module_release/
 